#!/bin/sh
# Setup
mdev -s
mount -t proc none /proc
mkdir -p /dev/pts
mount -vt devpts -o gid=4,mode=620 none /dev/pts
chmod 666 /dev/ptmx
stty -opost
echo 2 > /proc/sys/kernel/kptr_restrict
echo 1 > /proc/sys/kernel/dmesg_restrict

chown root:root /root/flag
chmod 400 /root/flag

# Install kernel driver
insmod /root/kmod.ko
mknod -m 666 /dev/kmod c `grep kmod /proc/devices | awk '{print $1;}'` 0

# User shell
echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n"
setsid cttyhack setuidgid 1001 sh

# Cleanup
umount /proc
poweroff -d 0 -f

